# Generated by Django 2.1.7 on 2019-03-23 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportCarriers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=3)),
                ('carrier', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'AirportCarriers',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Airports',
            },
        ),
        migrations.CreateModel(
            name='Delays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=3)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('late_aircraft', models.IntegerField()),
                ('weather', models.IntegerField()),
                ('security', models.IntegerField()),
                ('nas', models.IntegerField()),
                ('carrier', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Delays',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=3)),
                ('carrier', models.CharField(max_length=3)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('cancelled', models.IntegerField()),
                ('on_time', models.IntegerField()),
                ('total', models.IntegerField()),
                ('delayed', models.IntegerField()),
                ('diverted', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='MinutesDelayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=3)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('late_aircraft', models.IntegerField()),
                ('weather', models.IntegerField()),
                ('carrier', models.IntegerField()),
                ('security', models.IntegerField()),
                ('total', models.IntegerField()),
                ('nas', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
