# Generated by Django 2.1.7 on 2019-03-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delays',
            name='carrier',
            field=models.CharField(max_length=3),
        ),
    ]
