# Generated by Django 2.1.7 on 2019-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_auto_20190323_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delays',
        ),
        migrations.AlterField(
            model_name='minutesdelayed',
            name='carrier',
            field=models.CharField(max_length=3),
        ),
    ]
