# Generated by Django 2.1.7 on 2019-03-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0004_delays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinutesDelayed',
        ),
    ]
