# Generated by Django 2.1.7 on 2019-03-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0006_minutesdelayed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutesdelayed',
            options={'verbose_name_plural': 'MinutesDelayed'},
        ),
        migrations.AlterField(
            model_name='airportcarriers',
            name='airport',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='airportcarriers',
            name='carrier',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='delays',
            name='airport',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='delays',
            name='carrier',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='airport',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='carrier',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='minutesdelayed',
            name='airport',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='minutesdelayed',
            name='carrier',
            field=models.IntegerField(),
        ),
    ]
