# Generated by Django 2.1.7 on 2019-03-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0007_auto_20190324_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportcarriers',
            name='airport',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='airportcarriers',
            name='carrier',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='delays',
            name='airport',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='delays',
            name='carrier',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='flights',
            name='airport',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='flights',
            name='carrier',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='minutesdelayed',
            name='airport',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='minutesdelayed',
            name='carrier',
            field=models.CharField(max_length=3),
        ),
    ]
